// Generated by CoffeeScript 1.7.1
var Utils;

Utils = {
  getDocHeight: function() {
    return $(document).height();
  },
  getWinHeight: function() {
    return $(window).height();
  },
  getTargetHeight: function(target) {
    return target.height();
  },
  getScrollTop: function() {
    return $(document).scrollTop();
  },
  getTargetCenter: function(target) {
    return this.getWinHeight() / 2 - this.getTargetHeight(target) / 2 + this.getScrollTop();
  },
  onTouchPreventDefault: function(event) {
    return event.preventDefault();
  },
  fingerActionControl: function(eventType, action, onOff) {
    if (onOff === true) {
      if (typeof document.addEventListener !== 'undefined') {
        return document.addEventListener(eventType, action, false);
      } else {
        return document.attachEvent(eventType, action);
      }
    } else {
      if (typeof document.removeEventListener !== 'undefined') {
        return document.removeEventListener(eventType, action, false);
      } else {
        return document.detachEvent(eventType, action);
      }
    }
  },
  numberWithCommas: function(num) {
    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  },
  addBgLayer: function(bgLayerClassName) {
    var bgLayer, docHeight;
    docHeight = this.getDocHeight();
    $("body").append('<div class="' + bgLayerClassName + '"></div>');
    bgLayer = $("." + bgLayerClassName);
    return bgLayer.css("height", docHeight);
  },
  removeBgLayer: function(bgLayerClassName) {
    var bgLayer;
    bgLayer = $("." + bgLayerClassName);
    return bgLayer.remove();
  },
  addLayerPop: function(btnConfig) {
    var con, docFrag, index, _btn, _btnWrp, _i, _len, _msg, _ref, _wrp;
    docFrag = document.createDocumentFragment();
    _msg = this.createElem("div", btnConfig.msg.className, btnConfig.msg.text, null).outerHTML;
    _btn = "";
    _ref = btnConfig.btnContent;
    for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
      con = _ref[index];
      if (btnConfig.btnContent[index].className !== null) {
        _btn += this.createElem("div", btnConfig.btnContent[index].className, btnConfig.btnContent[index].text, null).outerHTML;
      }
    }
    _btnWrp = this.createElem("div", btnConfig.btnWrpClassName, _btn, null).outerHTML;
    _wrp = this.createElem("div", btnConfig.popWrpClassName, _msg + _btnWrp, null);
    docFrag.appendChild(_wrp);
    $("body").append(docFrag);
  },
  removeLayerPop: function(wrpClassName) {
    return $("." + wrpClassName).remove();
  },
  createElem: function(elementType, className, innerContent, action) {
    var tmpEl;
    tmpEl = document.createElement(elementType);
    tmpEl.className = className;
    if (action !== null) {
      tmpEl.addEventListener("mousedown", action, false);
    }
    tmpEl.innerHTML = innerContent;
    return tmpEl;
  }
};
